import fs from 'node:fs/promises';
import path from 'node:path';
import type { Plugin } from 'vite';

async function readJsonBody(req: any) {
  const chunks: Buffer[] = [];
  for await (const chunk of req) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  const text = Buffer.concat(chunks).toString('utf8');
  return text ? JSON.parse(text) : {};
}

function sendJson(res: any, statusCode: number, payload: Record<string, unknown>) {
  res.statusCode = statusCode;
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  res.end(JSON.stringify(payload));
}

function cssName(key: string) {
  return key.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
}

function generateVisualCss(state: any) {
  const lines = ['/* Generated by SB Visual Low-code Editor */'];

  Object.entries(state?.elements || {}).forEach(([id, raw]: [string, any]) => {
    const styles = raw?.styles || {};
    if (!Object.keys(styles).length && !raw?.hidden) return;

    lines.push(`[data-sb-edit-id="${String(id).replace(/"/g, '\\"')}"] {`);

    Object.entries(styles).forEach(([key, value]) => {
      if (value !== undefined && value !== null && value !== '') {
        lines.push(`  ${cssName(key)}: ${value};`);
      }
    });

    if (raw.hidden) lines.push('  display: none !important;');
    lines.push('}');
  });

  return lines.join('\n') + '\n';
}

export function sbDevEditorPlugin(): Plugin {
  return {
    name: 'sb-dev-editor-plugin',
    apply: 'serve',
    configureServer(server) {
      const root = server.config.root;
      const configPath = path.join(root, 'src', 'dev', 'devPageConfig.ts');
      const visualDir = path.join(root, 'public', 'app', 'assets', 'dev');
      const visualStatePath = path.join(visualDir, 'visual-editor-state.json');
      const visualCssPath = path.join(visualDir, 'visual-overrides.css');

      server.middlewares.use('/__sb_dev_editor/status', (_req, res) => {
        sendJson(res, 200, {
          status: 'success',
          mode: 'development-only',
          writableFile: configPath,
          visualStateFile: visualStatePath,
          note: 'Dev editor API is available only during npm run dev.',
        });
      });

      server.middlewares.use('/__sb_dev_editor/save-config', async (req, res) => {
        if (req.method !== 'POST') {
          sendJson(res, 405, { status: 'error', message: 'Method not allowed' });
          return;
        }

        try {
          const body = await readJsonBody(req);
          const text = `export const DEV_PAGE_CONFIG = ${JSON.stringify(body.config, null, 2)} as const;

export type DevPageConfig = typeof DEV_PAGE_CONFIG;
export type DevPreviewMode = keyof typeof DEV_PAGE_CONFIG.previewModes;
`;
          await fs.mkdir(path.dirname(configPath), { recursive: true });
          await fs.writeFile(configPath, text, 'utf8');
          sendJson(res, 200, { status: 'success', file: configPath, message: 'Saved devPageConfig.ts' });
        } catch (error) {
          sendJson(res, 500, { status: 'error', message: error instanceof Error ? error.message : String(error) });
        }
      });

      server.middlewares.use('/__sb_visual_editor/save', async (req, res) => {
        if (req.method !== 'POST') {
          sendJson(res, 405, { status: 'error', message: 'Method not allowed' });
          return;
        }

        try {
          const body = await readJsonBody(req);
          const state = {
            version: 1,
            updatedAt: new Date().toISOString(),
            elements: body.state?.elements || {},
            inserts: body.state?.inserts || [],
          };

          await fs.mkdir(visualDir, { recursive: true });
          await fs.writeFile(visualStatePath, JSON.stringify(state, null, 2), 'utf8');
          await fs.writeFile(visualCssPath, generateVisualCss(state), 'utf8');

          sendJson(res, 200, {
            status: 'success',
            stateFile: visualStatePath,
            cssFile: visualCssPath,
            message: 'Saved visual editor files',
          });
        } catch (error) {
          sendJson(res, 500, { status: 'error', message: error instanceof Error ? error.message : String(error) });
        }
      });
    },
  };
}
