-- 07_it_requests_schema.sql
create table if not exists it_requests (
  request_no text primary key,
  requested_at timestamptz not null default now(),
  objectives text,
  request_details text,
  reason_of_necessity text,
  spec text,
  requester_emp_id text references app_users(emp_id) on delete set null,
  requester_name text,
  requester_position text,
  requester_department text,
  requested_date date,
  desired_date date,
  manager_status request_status not null default 'pending',
  manager_date timestamptz,
  manager_emp_id text references app_users(emp_id) on delete set null,
  it_status request_status not null default 'pending',
  it_date timestamptz,
  it_emp_id text references app_users(emp_id) on delete set null,
  input_check text,
  input_repair text,
  input_other text,
  attachment_url text,
  pdf_report_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
