-- 15_QUOTATION_SUPABASE_SCHEMA.sql
-- Production quotation index/analysis schema.
--
-- Google Drive remains the binary-file source of truth.  This schema stores
-- searchable quotation data, calculations, Drive references, and a complete
-- normalized payload for reconciliation.  The browser must never write these
-- tables directly: Google Apps Script validates the public session and calls
-- the service-role-only sync RPC below.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.quotations (
  quotation_id text primary key,
  quotation_no text not null unique,
  client_request_id text,
  project_name text not null default '',
  revision bigint not null default 0,
  -- Kept as text for compatibility with the legacy Drive payload (max 100
  -- characters). New UI values remain ISO YYYY-MM-DD.
  quotation_date text not null default (current_date::text),
  status text not null default 'DRAFT',
  currency text not null default 'THB',

  -- Customer values are snapshots.  They intentionally do not reference a
  -- mutable customer master because a historical quotation must not change.
  customer_id text,
  customer_code text,
  customer_name text not null default '',
  customer_company text not null default '',
  customer_branch text not null default '',
  customer_address text not null default '',
  customer_phone text not null default '',
  customer_email text not null default '',
  customer_tax_id text not null default '',
  customer_contact_person text not null default '',
  customer_note text not null default '',

  quotation_note text not null default '',
  validity_days integer not null default 30,
  payment_terms text not null default '',
  delivery_terms text not null default '',

  vat_percent numeric(7,4) not null default 7,
  subtotal numeric(38,2) not null default 0,
  vat_amount numeric(38,2) not null default 0,
  grand_total numeric(38,2) not null default 0,
  total_proposed_cost numeric(38,2) not null default 0,
  total_item_cost numeric(38,2) not null default 0,
  total_cost numeric(38,2) not null default 0,
  cost_basis text not null default 'ITEM_UNIT_COST',
  gross_profit numeric(38,2) not null default 0,
  gp_percent numeric(38,4) not null default 0,

  report_version bigint not null default 1,
  drive_folder_id text,
  pdf_file_id text,
  pdf_url text,
  xlsx_file_id text,
  xlsx_url text,

  -- source_version is monotonic per quotation. source_hash is computed by the
  -- database from payload_json and detects same-version/different-data writes.
  source_version bigint not null default 1,
  source_hash text not null,
  payload_json jsonb not null default '{}'::jsonb,
  source_created_at timestamptz,
  source_updated_at timestamptz not null,
  last_synced_at timestamptz not null default now(),

  created_by_emp_id text not null references public.app_users(emp_id) on delete restrict,
  created_by_name text not null default '',
  updated_by_emp_id text references public.app_users(emp_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint quotations_id_not_blank check (length(btrim(quotation_id)) between 1 and 100),
  constraint quotations_no_not_blank check (length(btrim(quotation_no)) between 1 and 100),
  constraint quotations_revision_valid check (revision >= 0),
  constraint quotations_date_valid check (length(btrim(quotation_date)) between 1 and 100),
  constraint quotations_status_valid check (
    status in ('DRAFT','PENDING','SENT','APPROVED','REJECTED','CANCELLED','EXPIRED')
  ),
  constraint quotations_currency_valid check (currency ~ '^[A-Z]{3}$'),
  constraint quotations_validity_days_valid check (validity_days between 0 and 3650),
  constraint quotations_vat_valid check (vat_percent between 0 and 100),
  constraint quotations_amounts_nonnegative check (
    subtotal >= 0 and vat_amount >= 0 and grand_total >= 0
    and total_proposed_cost >= 0 and total_item_cost >= 0 and total_cost >= 0
  ),
  constraint quotations_cost_basis_valid check (cost_basis in ('ITEM_UNIT_COST','SB_COST_NOTES')),
  constraint quotations_report_version_valid check (report_version >= 1),
  constraint quotations_source_version_valid check (source_version >= 1),
  constraint quotations_source_hash_valid check (source_hash ~ '^[0-9a-f]{32}$'),
  constraint quotations_payload_object check (jsonb_typeof(payload_json) = 'object')
);

create table if not exists public.quotation_items (
  id bigint generated by default as identity primary key,
  quotation_id text not null references public.quotations(quotation_id) on delete cascade,
  source_item_id text,
  item_no integer not null,
  product_id text,
  product_ref text not null default '',
  product_name text not null default '',
  description text not null default '',
  unit text not null default '',
  quantity numeric(38,4) not null default 0,
  unit_price numeric(38,4) not null default 0,
  amount numeric(38,2) not null default 0,
  unit_cost numeric(38,4) not null default 0,
  cost_amount numeric(38,2) not null default 0,
  remark text not null default '',
  picture_file_id text,
  picture_url text,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quotation_items_line_unique unique (quotation_id, item_no),
  constraint quotation_items_number_valid check (item_no between 1 and 200),
  constraint quotation_items_amounts_valid check (
    quantity >= 0 and unit_price >= 0 and amount >= 0 and unit_cost >= 0 and cost_amount >= 0
  ),
  constraint quotation_items_payload_object check (jsonb_typeof(payload_json) = 'object')
);

create table if not exists public.quotation_cost_notes (
  id bigint generated by default as identity primary key,
  quotation_id text not null references public.quotations(quotation_id) on delete cascade,
  source_cost_note_id text,
  note_no integer not null,
  description text not null default '',
  proposed_cost numeric(38,2) not null default 0,
  sb_cost numeric(38,2) not null default 0,
  gp_percent numeric(38,4) not null default 0,
  note text not null default '',
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quotation_cost_notes_line_unique unique (quotation_id, note_no),
  constraint quotation_cost_notes_number_valid check (note_no between 1 and 100),
  constraint quotation_cost_notes_amounts_valid check (proposed_cost >= 0 and sb_cost >= 0),
  constraint quotation_cost_notes_payload_object check (jsonb_typeof(payload_json) = 'object')
);

create table if not exists public.quotation_files (
  id bigint generated by default as identity primary key,
  quotation_id text not null references public.quotations(quotation_id) on delete cascade,
  drive_file_id text not null,
  file_kind text not null,
  file_name text not null default '',
  mime_type text not null default '',
  bucket text not null default '',
  view_url text not null default '',
  direct_url text not null default '',
  registry_source text not null default '',
  report_version bigint,
  is_current boolean not null default true,
  uploaded_by_emp_id text references public.app_users(emp_id) on delete set null,
  source_created_at timestamptz,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quotation_files_source_unique unique (quotation_id, drive_file_id, file_kind),
  constraint quotation_files_id_not_blank check (length(btrim(drive_file_id)) between 1 and 300),
  constraint quotation_files_kind_not_blank check (length(btrim(file_kind)) between 1 and 100),
  constraint quotation_files_report_version_valid check (report_version is null or report_version >= 1),
  constraint quotation_files_payload_object check (jsonb_typeof(payload_json) = 'object')
);

-- Type normalization makes this migration safe to rerun over an earlier draft
-- of the quotation schema without dropping data.
alter table public.quotations alter column quotation_date drop default;
alter table public.quotations alter column quotation_date type text using quotation_date::text;
alter table public.quotations alter column quotation_date set default (current_date::text);
alter table public.quotations alter column revision type bigint using revision::bigint;
alter table public.quotations alter column report_version type bigint using report_version::bigint;
alter table public.quotations alter column subtotal type numeric(38,2) using subtotal::numeric(38,2);
alter table public.quotations alter column vat_amount type numeric(38,2) using vat_amount::numeric(38,2);
alter table public.quotations alter column grand_total type numeric(38,2) using grand_total::numeric(38,2);
alter table public.quotations alter column total_proposed_cost type numeric(38,2) using total_proposed_cost::numeric(38,2);
alter table public.quotations alter column total_item_cost type numeric(38,2) using total_item_cost::numeric(38,2);
alter table public.quotations alter column total_cost type numeric(38,2) using total_cost::numeric(38,2);
alter table public.quotations alter column gross_profit type numeric(38,2) using gross_profit::numeric(38,2);
alter table public.quotations alter column gp_percent type numeric(38,4) using gp_percent::numeric(38,4);
alter table public.quotation_items alter column quantity type numeric(38,4) using quantity::numeric(38,4);
alter table public.quotation_items alter column unit_price type numeric(38,4) using unit_price::numeric(38,4);
alter table public.quotation_items alter column amount type numeric(38,2) using amount::numeric(38,2);
alter table public.quotation_items alter column unit_cost type numeric(38,4) using unit_cost::numeric(38,4);
alter table public.quotation_items alter column cost_amount type numeric(38,2) using cost_amount::numeric(38,2);
alter table public.quotation_cost_notes alter column proposed_cost type numeric(38,2) using proposed_cost::numeric(38,2);
alter table public.quotation_cost_notes alter column sb_cost type numeric(38,2) using sb_cost::numeric(38,2);
alter table public.quotation_cost_notes alter column gp_percent type numeric(38,4) using gp_percent::numeric(38,4);
alter table public.quotation_files alter column report_version type bigint using report_version::bigint;

do $$ begin
  alter table public.quotations
    add constraint quotations_date_valid
    check (length(btrim(quotation_date)) between 1 and 100);
exception when duplicate_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create unique index if not exists uq_quotations_owner_client_request
  on public.quotations(created_by_emp_id, client_request_id)
  where client_request_id is not null and btrim(client_request_id) <> '';

create index if not exists idx_quotations_owner_updated
  on public.quotations(created_by_emp_id, updated_at desc);
create index if not exists idx_quotations_status_date
  on public.quotations(status, quotation_date desc);
create index if not exists idx_quotations_customer_name
  on public.quotations(lower(customer_name));
create index if not exists idx_quotations_customer_company
  on public.quotations(lower(customer_company));
create index if not exists idx_quotations_source_sync
  on public.quotations(source_updated_at desc, last_synced_at desc);
create index if not exists idx_quotation_items_parent
  on public.quotation_items(quotation_id, item_no);
create index if not exists idx_quotation_cost_notes_parent
  on public.quotation_cost_notes(quotation_id, note_no);
create index if not exists idx_quotation_files_parent_kind
  on public.quotation_files(quotation_id, file_kind, is_current);
create index if not exists idx_quotation_files_drive_id
  on public.quotation_files(drive_file_id);

-- Reuse the project's canonical updated_at trigger function.
drop trigger if exists trg_quotations_updated_at on public.quotations;
create trigger trg_quotations_updated_at
before update on public.quotations
for each row execute function public.set_updated_at();

drop trigger if exists trg_quotation_items_updated_at on public.quotation_items;
create trigger trg_quotation_items_updated_at
before update on public.quotation_items
for each row execute function public.set_updated_at();

drop trigger if exists trg_quotation_cost_notes_updated_at on public.quotation_cost_notes;
create trigger trg_quotation_cost_notes_updated_at
before update on public.quotation_cost_notes
for each row execute function public.set_updated_at();

drop trigger if exists trg_quotation_files_updated_at on public.quotation_files;
create trigger trg_quotation_files_updated_at
before update on public.quotation_files
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Private parsing helpers used by the service-role sync RPC
-- ---------------------------------------------------------------------------

create or replace function public.quotation_safe_numeric(p_value text, p_default numeric default 0)
returns numeric
language plpgsql
immutable
set search_path = public
as $$
begin
  if p_value is null or btrim(p_value) = '' then return p_default; end if;
  return p_value::numeric;
exception when invalid_text_representation or numeric_value_out_of_range then
  return p_default;
end $$;

create or replace function public.quotation_safe_integer(p_value text, p_default integer default 0)
returns integer
language plpgsql
immutable
set search_path = public
as $$
begin
  if p_value is null or btrim(p_value) = '' then return p_default; end if;
  return trunc(p_value::numeric)::integer;
exception when invalid_text_representation or numeric_value_out_of_range then
  return p_default;
end $$;

create or replace function public.quotation_safe_bigint(p_value text, p_default bigint default 0)
returns bigint
language plpgsql
immutable
set search_path = public
as $$
begin
  if p_value is null or btrim(p_value) = '' then return p_default; end if;
  return trunc(p_value::numeric)::bigint;
exception when invalid_text_representation or numeric_value_out_of_range then
  return p_default;
end $$;

create or replace function public.quotation_safe_date(p_value text, p_default date default current_date)
returns date
language plpgsql
stable
set search_path = public
as $$
begin
  if p_value is null or btrim(p_value) = '' then return p_default; end if;
  return p_value::date;
exception when invalid_datetime_format or datetime_field_overflow then
  return p_default;
end $$;

create or replace function public.quotation_safe_timestamptz(p_value text, p_default timestamptz default now())
returns timestamptz
language plpgsql
stable
set search_path = public
as $$
begin
  if p_value is null or btrim(p_value) = '' then return p_default; end if;
  return p_value::timestamptz;
exception when invalid_datetime_format or datetime_field_overflow then
  return p_default;
end $$;

-- ---------------------------------------------------------------------------
-- Service-role session validation
-- ---------------------------------------------------------------------------

create or replace function public.validate_quotation_session_for_service(p_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_emp_id text;
  v_role public.app_role;
  v_expires_at timestamptz;
begin
  select u.emp_id, u.role, s.expires_at
    into v_emp_id, v_role, v_expires_at
  from public.public_sessions s
  join public.app_users u on u.emp_id = s.emp_id
  where s.session_token = p_token
    and s.revoked_at is null
    and s.expires_at > now()
    and u.status = 'active'
  limit 1;

  if not found then
    return jsonb_build_object('status','error','message','SESSION_EXPIRED');
  end if;

  return jsonb_build_object(
    'status','success',
    'emp_id',v_emp_id,
    'role',lower(v_role::text),
    'expires_at',v_expires_at
  );
end $$;

-- ---------------------------------------------------------------------------
-- Atomic Drive -> Supabase synchronization
-- ---------------------------------------------------------------------------

create or replace function public.quotation_sync_from_drive_core(
  p_token uuid,
  p_quotation jsonb,
  p_reconcile boolean
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record jsonb;
  v_payload jsonb;
  v_items jsonb;
  v_cost_notes jsonb;
  v_files jsonb;
  v_item jsonb;
  v_cost_note jsonb;
  v_file jsonb;
  v_ordinality bigint;
  v_emp_id text;
  v_owner_emp_id text;
  v_updated_by_emp_id text;
  v_role public.app_role;
  v_id text;
  v_no text;
  v_status text;
  v_source_version bigint;
  v_source_hash text;
  v_existing public.quotations%rowtype;
  v_now timestamptz := now();
  v_subtotal numeric(38,2);
  v_vat_percent numeric(7,4);
  v_vat_amount numeric(38,2);
  v_grand_total numeric(38,2);
  v_total_proposed_cost numeric(38,2);
  v_total_item_cost numeric(38,2);
  v_total_cost numeric(38,2);
  v_gross_profit numeric(38,2);
  v_gp_percent numeric(38,4);
  v_has_sb_cost boolean;
begin
  if p_quotation is null or jsonb_typeof(p_quotation) <> 'object' then
    return jsonb_build_object('status','error','message','INVALID_QUOTATION_ENVELOPE');
  end if;

  if p_reconcile and p_token is not null then
    return jsonb_build_object('status','error','message','RECONCILIATION_TOKEN_MUST_BE_NULL');
  end if;
  if not p_reconcile and p_token is null then
    return jsonb_build_object('status','error','message','SESSION_TOKEN_REQUIRED');
  end if;

  v_record := case
    when jsonb_typeof(p_quotation->'record') = 'object' then p_quotation->'record'
    else p_quotation
  end;
  v_payload := case
    when jsonb_typeof(p_quotation->'payload_json') = 'object' then p_quotation->'payload_json'
    when jsonb_typeof(v_record->'payload_json') = 'object' then v_record->'payload_json'
    else v_record
  end;
  v_items := case
    when jsonb_typeof(p_quotation->'items') = 'array' then p_quotation->'items'
    when jsonb_typeof(v_payload->'items') = 'array' then v_payload->'items'
    when jsonb_typeof(v_payload->'quotation_items') = 'array' then v_payload->'quotation_items'
    else '[]'::jsonb
  end;
  v_cost_notes := case
    when jsonb_typeof(p_quotation->'cost_notes') = 'array' then p_quotation->'cost_notes'
    when jsonb_typeof(v_payload->'costNotes') = 'array' then v_payload->'costNotes'
    when jsonb_typeof(v_payload->'cost_notes') = 'array' then v_payload->'cost_notes'
    else '[]'::jsonb
  end;
  v_files := case
    when jsonb_typeof(p_quotation->'files') = 'array' then p_quotation->'files'
    when jsonb_typeof(v_payload->'files') = 'array' then v_payload->'files'
    else '[]'::jsonb
  end;

  if jsonb_array_length(v_items) > 200 then
    return jsonb_build_object('status','error','message','TOO_MANY_QUOTATION_ITEMS');
  end if;
  if jsonb_array_length(v_cost_notes) > 100 then
    return jsonb_build_object('status','error','message','TOO_MANY_QUOTATION_COST_NOTES');
  end if;
  -- Apps Script can retain 250 trusted uploads plus generated PDF/XLSX refs.
  if jsonb_array_length(v_files) > 300 then
    return jsonb_build_object('status','error','message','TOO_MANY_QUOTATION_FILES');
  end if;

  v_id := btrim(coalesce(v_record->>'quotation_id', v_record->>'quotationId', v_record->>'id', ''));
  v_no := btrim(coalesce(v_record->>'quotation_no', v_record->>'quotationNo', ''));
  v_status := upper(btrim(coalesce(v_record->>'status', 'DRAFT')));
  v_source_version := public.quotation_safe_bigint(
    coalesce(v_record->>'source_version', v_record->>'sourceVersion',
             v_record->>'report_version', v_record->>'reportVersion'), 1
  );
  v_source_hash := md5(jsonb_build_object(
    'record', v_record - 'source_hash' - 'sourceHash',
    'payload_json', v_payload,
    'items', v_items,
    'cost_notes', v_cost_notes,
    'files', v_files
  )::text);

  -- Immediate writes carry the original public-session token. A NULL token is
  -- reserved for the service-role-only time-trigger reconciliation job; that
  -- path preserves the stored owner (or uses the authoritative Drive owner on
  -- first import). Browser roles cannot execute this function.
  if not p_reconcile then
    select u.emp_id, u.role
      into v_emp_id, v_role
    from public.public_sessions s
    join public.app_users u on u.emp_id = s.emp_id
    where s.session_token = p_token
      and s.revoked_at is null
      and s.expires_at > v_now
      and u.status = 'active'
    limit 1;

    if not found then
      return jsonb_build_object('status','error','message','SESSION_EXPIRED');
    end if;
  end if;

  if v_id = '' or length(v_id) > 100 then
    return jsonb_build_object('status','error','message','INVALID_QUOTATION_ID');
  end if;
  if v_no = '' or length(v_no) > 100 then
    return jsonb_build_object('status','error','message','INVALID_QUOTATION_NO');
  end if;
  if v_status not in ('DRAFT','PENDING','SENT','APPROVED','REJECTED','CANCELLED','EXPIRED') then
    return jsonb_build_object('status','error','message','INVALID_QUOTATION_STATUS');
  end if;
  if v_source_version < 1 then
    return jsonb_build_object('status','error','message','INVALID_SOURCE_VERSION');
  end if;

  -- Serialize concurrent retries for the same source identity and number.
  perform pg_advisory_xact_lock(hashtextextended('quotation-id:' || v_id, 0));
  perform pg_advisory_xact_lock(hashtextextended('quotation-no:' || v_no, 0));

  select * into v_existing
  from public.quotations
  where quotation_id = v_id
  for update;

  if found then
    if not p_reconcile
       and v_existing.created_by_emp_id <> v_emp_id
       and v_role not in ('manager','admin','admin_it','dev') then
      return jsonb_build_object('status','error','message','QUOTATION_ACCESS_DENIED');
    end if;

    if v_source_version < v_existing.source_version then
      return jsonb_build_object(
        'status','success','action','stale_noop','stale',true,
        'quotation_id',v_id,'quotation_no',v_existing.quotation_no,
        'source_version',v_existing.source_version,'source_hash',v_existing.source_hash,
        'synced_at',v_existing.last_synced_at
      );
    end if;

    if v_source_version = v_existing.source_version then
      if v_source_hash = v_existing.source_hash then
        return jsonb_build_object(
          'status','success','action','idempotent_noop','idempotent',true,
          'quotation_id',v_id,'quotation_no',v_existing.quotation_no,
          'source_version',v_existing.source_version,'source_hash',v_existing.source_hash,
          'synced_at',v_existing.last_synced_at
        );
      end if;
      return jsonb_build_object(
        'status','error','message','VERSION_COLLISION',
        'quotation_id',v_id,'stored_version',v_existing.source_version,
        'incoming_version',v_source_version
      );
    end if;
  else
    if exists(select 1 from public.quotations q where q.quotation_no = v_no) then
      return jsonb_build_object('status','error','message','QUOTATION_NO_CONFLICT');
    end if;
  end if;

  if not p_reconcile then
    -- User-initiated writes derive ownership and updater identity from the live
    -- database session. On the first SQL mirror of a legacy Drive row, a
    -- manager may preserve its canonical owner, but only if that employee
    -- exists; ordinary users can never assign ownership to somebody else.
    if v_existing.created_by_emp_id is not null then
      v_owner_emp_id := v_existing.created_by_emp_id;
    else
      v_owner_emp_id := nullif(btrim(coalesce(
        v_record->>'created_by_emp_id', v_record->>'createdByEmpId', ''
      )), '');
      if v_owner_emp_id is null then
        v_owner_emp_id := v_emp_id;
      elsif v_owner_emp_id <> v_emp_id then
        if v_role not in ('manager','admin','admin_it','dev')
           or not exists(select 1 from public.app_users u where u.emp_id = v_owner_emp_id) then
          return jsonb_build_object('status','error','message','QUOTATION_OWNER_MISMATCH');
        end if;
      end if;
    end if;
    v_updated_by_emp_id := v_emp_id;
  else
    -- Background reconciliation runs only through service_role. Existing
    -- ownership is immutable; a first import must name a real app_users row.
    v_owner_emp_id := coalesce(
      v_existing.created_by_emp_id,
      nullif(btrim(coalesce(v_record->>'created_by_emp_id', v_record->>'createdByEmpId', '')), '')
    );
    if v_owner_emp_id is null
       or not exists(select 1 from public.app_users u where u.emp_id = v_owner_emp_id) then
      return jsonb_build_object('status','error','message','INVALID_RECONCILIATION_OWNER');
    end if;
    v_updated_by_emp_id := nullif(btrim(coalesce(
      v_record->>'updated_by_emp_id', v_record->>'updatedByEmpId', ''
    )), '');
    if v_updated_by_emp_id is null
       or not exists(select 1 from public.app_users u where u.emp_id = v_updated_by_emp_id) then
      v_updated_by_emp_id := v_owner_emp_id;
    end if;
  end if;

  v_vat_percent := least(100, greatest(0, public.quotation_safe_numeric(
    coalesce(v_record->>'vat_percent', v_record->>'vatPercent', v_payload->>'vat_percent', v_payload->>'vatPercent'), 7
  )))::numeric(7,4);

  insert into public.quotations (
    quotation_id, quotation_no, client_request_id, project_name, revision,
    quotation_date, status, currency,
    customer_id, customer_code, customer_name, customer_company, customer_branch,
    customer_address, customer_phone, customer_email, customer_tax_id,
    customer_contact_person, customer_note,
    quotation_note, validity_days, payment_terms, delivery_terms, vat_percent,
    report_version, drive_folder_id, pdf_file_id, pdf_url, xlsx_file_id, xlsx_url,
    source_version, source_hash, payload_json, source_created_at, source_updated_at,
    last_synced_at, created_by_emp_id, created_by_name, updated_by_emp_id
  ) values (
    v_id, v_no,
    nullif(btrim(coalesce(v_record->>'client_request_id', v_record->>'clientRequestId', '')), ''),
    coalesce(v_record->>'project_name', v_record->>'projectName', ''),
    greatest(0, public.quotation_safe_bigint(v_record->>'revision', 0)),
    left(coalesce(nullif(btrim(coalesce(v_record->>'quotation_date', v_record->>'quotationDate')), ''), current_date::text), 100),
    v_status,
    case
      when upper(coalesce(nullif(btrim(v_record->>'currency'), ''), 'THB')) ~ '^[A-Z]{3}$'
        then upper(coalesce(nullif(btrim(v_record->>'currency'), ''), 'THB'))
      else 'THB'
    end,
    nullif(btrim(coalesce(v_record->>'customer_id', v_payload#>>'{customer,id}', '')), ''),
    nullif(btrim(coalesce(v_record->>'customer_code', v_payload#>>'{customer,code}', '')), ''),
    coalesce(v_record->>'customer_name', v_payload#>>'{customer,name}', ''),
    coalesce(v_record->>'customer_company', v_payload#>>'{customer,company}', ''),
    coalesce(v_record->>'customer_branch', v_payload#>>'{customer,branch}', ''),
    coalesce(v_record->>'customer_address', v_payload#>>'{customer,address}', ''),
    coalesce(v_record->>'customer_phone', v_payload#>>'{customer,phone}', ''),
    coalesce(v_record->>'customer_email', v_payload#>>'{customer,email}', ''),
    coalesce(v_record->>'customer_tax_id', v_payload#>>'{customer,taxId}', v_payload#>>'{customer,tax_id}', ''),
    coalesce(v_record->>'customer_contact_person', v_payload#>>'{customer,contactPerson}', v_payload#>>'{customer,contact_person}', ''),
    coalesce(v_record->>'customer_note', v_payload#>>'{customer,note}', ''),
    coalesce(v_record->>'quotation_note', v_payload->>'note', ''),
    least(3650, greatest(0, public.quotation_safe_integer(
      coalesce(v_record->>'validity_days', v_payload#>>'{terms,validityDays}', v_payload#>>'{terms,validity_days}'), 30
    ))),
    coalesce(v_record->>'payment_terms', v_payload#>>'{terms,paymentTerms}', v_payload#>>'{terms,payment_terms}', ''),
    coalesce(v_record->>'delivery_terms', v_payload#>>'{terms,deliveryTerms}', v_payload#>>'{terms,delivery_terms}', ''),
    v_vat_percent,
    greatest(1, public.quotation_safe_bigint(coalesce(v_record->>'report_version', v_record->>'reportVersion'), 1)),
    nullif(btrim(coalesce(v_record->>'drive_folder_id', '')), ''),
    nullif(btrim(coalesce(v_record->>'pdf_file_id', v_payload->>'pdfFileId', v_payload->>'pdf_file_id', '')), ''),
    nullif(btrim(coalesce(v_record->>'pdf_url', v_payload->>'pdfUrl', v_payload->>'pdf_url', '')), ''),
    nullif(btrim(coalesce(v_record->>'xlsx_file_id', v_payload->>'xlsxFileId', v_payload->>'xlsx_file_id', '')), ''),
    nullif(btrim(coalesce(v_record->>'xlsx_url', v_payload->>'xlsxUrl', v_payload->>'xlsx_url', '')), ''),
    v_source_version, v_source_hash, v_payload,
    public.quotation_safe_timestamptz(
      coalesce(v_record->>'source_created_at', v_record->>'created_at', v_record->>'createdAt'), v_now
    ),
    public.quotation_safe_timestamptz(
      coalesce(v_record->>'source_updated_at', v_record->>'updated_at', v_record->>'updatedAt'), v_now
    ),
    v_now,
    v_owner_emp_id,
    coalesce(nullif(v_existing.created_by_name, ''), v_record->>'created_by_name', v_record->>'createdByName', ''),
    v_updated_by_emp_id
  )
  on conflict (quotation_id) do update set
    quotation_no = excluded.quotation_no,
    client_request_id = excluded.client_request_id,
    project_name = excluded.project_name,
    revision = excluded.revision,
    quotation_date = excluded.quotation_date,
    status = excluded.status,
    currency = excluded.currency,
    customer_id = excluded.customer_id,
    customer_code = excluded.customer_code,
    customer_name = excluded.customer_name,
    customer_company = excluded.customer_company,
    customer_branch = excluded.customer_branch,
    customer_address = excluded.customer_address,
    customer_phone = excluded.customer_phone,
    customer_email = excluded.customer_email,
    customer_tax_id = excluded.customer_tax_id,
    customer_contact_person = excluded.customer_contact_person,
    customer_note = excluded.customer_note,
    quotation_note = excluded.quotation_note,
    validity_days = excluded.validity_days,
    payment_terms = excluded.payment_terms,
    delivery_terms = excluded.delivery_terms,
    vat_percent = excluded.vat_percent,
    report_version = excluded.report_version,
    drive_folder_id = excluded.drive_folder_id,
    pdf_file_id = excluded.pdf_file_id,
    pdf_url = excluded.pdf_url,
    xlsx_file_id = excluded.xlsx_file_id,
    xlsx_url = excluded.xlsx_url,
    source_version = excluded.source_version,
    source_hash = excluded.source_hash,
    payload_json = excluded.payload_json,
    source_updated_at = excluded.source_updated_at,
    last_synced_at = excluded.last_synced_at,
    updated_by_emp_id = excluded.updated_by_emp_id;

  delete from public.quotation_items where quotation_id = v_id;
  v_ordinality := 0;
  for v_item in select value from jsonb_array_elements(v_items)
  loop
    v_ordinality := v_ordinality + 1;
    insert into public.quotation_items (
      quotation_id, source_item_id, item_no, product_id, product_ref, product_name,
      description, unit, quantity, unit_price, amount, unit_cost, cost_amount,
      remark, picture_file_id, picture_url, payload_json
    ) values (
      v_id,
      nullif(btrim(coalesce(v_item->>'id', v_item->>'item_id', '')), ''),
      v_ordinality::integer,
      nullif(btrim(coalesce(v_item->>'product_id', v_item->>'productId', '')), ''),
      coalesce(v_item->>'product_ref', v_item->>'productRef', ''),
      coalesce(v_item->>'product_name', v_item->>'productName', ''),
      coalesce(v_item->>'description', ''),
      coalesce(v_item->>'unit', ''),
      greatest(0, public.quotation_safe_numeric(coalesce(v_item->>'quantity', v_item->>'qty'), 0)),
      greatest(0, public.quotation_safe_numeric(coalesce(v_item->>'unit_price', v_item->>'unitPrice'), 0)),
      round(
        greatest(0, public.quotation_safe_numeric(coalesce(v_item->>'quantity', v_item->>'qty'), 0))
        * greatest(0, public.quotation_safe_numeric(coalesce(v_item->>'unit_price', v_item->>'unitPrice'), 0)), 2
      ),
      greatest(0, public.quotation_safe_numeric(coalesce(v_item->>'unit_cost', v_item->>'unitCost', v_item->>'cost'), 0)),
      round(
        greatest(0, public.quotation_safe_numeric(coalesce(v_item->>'quantity', v_item->>'qty'), 0))
        * greatest(0, public.quotation_safe_numeric(coalesce(v_item->>'unit_cost', v_item->>'unitCost', v_item->>'cost'), 0)), 2
      ),
      coalesce(v_item->>'remark', v_item->>'note', ''),
      nullif(btrim(coalesce(v_item->>'picture_file_id', v_item->>'pictureFileId', v_item->>'image_file_id', v_item->>'imageFileId', '')), ''),
      nullif(btrim(coalesce(v_item->>'picture_url', v_item->>'pictureUrl', v_item->>'image_url', v_item->>'imageUrl', '')), ''),
      v_item
    );
  end loop;

  delete from public.quotation_cost_notes where quotation_id = v_id;
  v_ordinality := 0;
  for v_cost_note in select value from jsonb_array_elements(v_cost_notes)
  loop
    v_ordinality := v_ordinality + 1;
    insert into public.quotation_cost_notes (
      quotation_id, source_cost_note_id, note_no, description, proposed_cost,
      sb_cost, gp_percent, note, payload_json
    ) values (
      v_id,
      nullif(btrim(coalesce(v_cost_note->>'id', v_cost_note->>'cost_note_id', '')), ''),
      v_ordinality::integer,
      coalesce(v_cost_note->>'description', ''),
      greatest(0, round(public.quotation_safe_numeric(
        coalesce(v_cost_note->>'proposed_cost', v_cost_note->>'proposedCost', v_cost_note->>'pcost'), 0
      ), 2)),
      greatest(0, round(public.quotation_safe_numeric(
        coalesce(v_cost_note->>'sb_cost', v_cost_note->>'sbCost', v_cost_note->>'sbcost'), 0
      ), 2)),
      public.quotation_safe_numeric(coalesce(v_cost_note->>'gp_percent', v_cost_note->>'gpPercent'), 0),
      coalesce(v_cost_note->>'note', v_cost_note->>'remark', ''),
      v_cost_note
    );
  end loop;

  delete from public.quotation_files where quotation_id = v_id;
  for v_file in select value from jsonb_array_elements(v_files)
  loop
    if btrim(coalesce(v_file->>'drive_file_id', v_file->>'file_id', v_file->>'fileId', '')) <> '' then
      insert into public.quotation_files (
        quotation_id, drive_file_id, file_kind, file_name, mime_type, bucket,
        view_url, direct_url, registry_source, report_version, is_current,
        uploaded_by_emp_id, source_created_at, payload_json
      ) values (
        v_id,
        btrim(coalesce(v_file->>'drive_file_id', v_file->>'file_id', v_file->>'fileId')),
        coalesce(nullif(btrim(coalesce(v_file->>'file_kind', v_file->>'kind', '')), ''), 'quotation_attachments'),
        coalesce(v_file->>'file_name', v_file->>'fileName', v_file->>'name', ''),
        coalesce(v_file->>'mime_type', v_file->>'mimeType', ''),
        coalesce(v_file->>'bucket', ''),
        coalesce(v_file->>'view_url', v_file->>'viewUrl', v_file->>'url', ''),
        coalesce(v_file->>'direct_url', v_file->>'directUrl', v_file->>'download_url', ''),
        coalesce(v_file->>'registry_source', v_file->>'registrySource', v_file->>'source', ''),
        nullif(public.quotation_safe_bigint(
          coalesce(v_file->>'report_version', v_file->>'reportVersion'), 0
        ), 0),
        case lower(btrim(coalesce(v_file->>'is_current', v_file->>'isCurrent', 'true')))
          when 'false' then false when 'f' then false when '0' then false when 'no' then false
          else true
        end,
        v_updated_by_emp_id,
        public.quotation_safe_timestamptz(
          coalesce(v_file->>'source_created_at', v_file->>'created_at', v_file->>'createdAt'), v_now
        ),
        v_file
      )
      on conflict (quotation_id, drive_file_id, file_kind) do update set
        file_name = excluded.file_name,
        mime_type = excluded.mime_type,
        bucket = excluded.bucket,
        view_url = excluded.view_url,
        direct_url = excluded.direct_url,
        registry_source = excluded.registry_source,
        report_version = excluded.report_version,
        is_current = excluded.is_current,
        payload_json = excluded.payload_json,
        updated_at = v_now;
    end if;
  end loop;

  select
    coalesce(round(sum(i.amount), 2), 0),
    coalesce(round(sum(i.cost_amount), 2), 0)
  into v_subtotal, v_total_item_cost
  from public.quotation_items i
  where i.quotation_id = v_id;

  select
    coalesce(round(sum(c.proposed_cost), 2), 0),
    coalesce(round(sum(c.sb_cost), 2), 0),
    coalesce(bool_or(c.sb_cost > 0), false)
  into v_total_proposed_cost, v_total_cost, v_has_sb_cost
  from public.quotation_cost_notes c
  where c.quotation_id = v_id;

  if not v_has_sb_cost then v_total_cost := v_total_item_cost; end if;
  v_vat_amount := round(v_subtotal * v_vat_percent / 100, 2);
  v_grand_total := round(v_subtotal + v_vat_amount, 2);
  v_gross_profit := round(v_subtotal - v_total_cost, 2);
  v_gp_percent := case when v_subtotal = 0 then 0 else round(v_gross_profit / v_subtotal * 100, 2) end;

  update public.quotations
  set subtotal = v_subtotal,
      vat_amount = v_vat_amount,
      grand_total = v_grand_total,
      total_proposed_cost = v_total_proposed_cost,
      total_item_cost = v_total_item_cost,
      total_cost = v_total_cost,
      cost_basis = case when v_has_sb_cost then 'SB_COST_NOTES' else 'ITEM_UNIT_COST' end,
      gross_profit = v_gross_profit,
      gp_percent = v_gp_percent,
      updated_at = v_now
  where quotation_id = v_id;

  return jsonb_build_object(
    'status','success','action',case when v_existing.quotation_id is null then 'inserted' else 'updated' end,
    'quotation_id',v_id,'quotation_no',v_no,
    'source_version',v_source_version,'source_hash',v_source_hash,
    'synced_at',v_now,
    'totals',jsonb_build_object(
      'subtotal',v_subtotal,'vat_percent',v_vat_percent,'vat_amount',v_vat_amount,
      'grand_total',v_grand_total,'total_proposed_cost',v_total_proposed_cost,
      'total_item_cost',v_total_item_cost,'total_cost',v_total_cost,
      'gross_profit',v_gross_profit,'gp_percent',v_gp_percent
    )
  );
end $$;

-- User-initiated synchronization. The token is mandatory and ownership comes
-- only from the current active app_users row behind that token.
create or replace function public.sync_quotation_from_drive(
  p_token uuid,
  p_quotation jsonb
)
returns jsonb
language sql
security definer
set search_path = pg_catalog, public
as $$
  select public.quotation_sync_from_drive_core(p_token, p_quotation, false)
$$;

-- Time-trigger reconciliation. This separately named entry point has no user
-- token and is executable only by service_role. It preserves an existing SQL
-- owner; first import accepts only an owner that exists in app_users.
create or replace function public.reconcile_quotation_from_drive(p_quotation jsonb)
returns jsonb
language sql
security definer
set search_path = pg_catalog, public
as $$
  select public.quotation_sync_from_drive_core(null, p_quotation, true)
$$;

-- ---------------------------------------------------------------------------
-- RLS defense in depth. There are intentionally zero table policies: all
-- browser-facing roles use Apps Script, while service_role uses the RPCs.
-- ---------------------------------------------------------------------------

alter table public.quotations enable row level security;
alter table public.quotations force row level security;
alter table public.quotation_items enable row level security;
alter table public.quotation_items force row level security;
alter table public.quotation_cost_notes enable row level security;
alter table public.quotation_cost_notes force row level security;
alter table public.quotation_files enable row level security;
alter table public.quotation_files force row level security;

drop policy if exists "quotation owners or managers read" on public.quotations;
drop policy if exists "quotation owners or managers insert" on public.quotations;
drop policy if exists "quotation owners or managers update" on public.quotations;
drop policy if exists "quotation owners or managers delete" on public.quotations;
drop policy if exists "quotation item access follows parent" on public.quotation_items;
drop policy if exists "quotation cost access follows parent" on public.quotation_cost_notes;
drop policy if exists "quotation file access follows parent" on public.quotation_files;

-- Remove helper functions from an earlier draft after their policies are gone.
drop function if exists public.quotation_auth_can_access(text);
drop function if exists public.quotation_auth_can_manage_all();

-- No quotation table is callable/readable from the public browser roles.  The
-- Apps Script service role is the only writer, through sync_quotation_from_drive.
revoke all on table public.quotations from public, anon, authenticated;
revoke all on table public.quotation_items from public, anon, authenticated;
revoke all on table public.quotation_cost_notes from public, anon, authenticated;
revoke all on table public.quotation_files from public, anon, authenticated;
revoke all on sequence public.quotation_items_id_seq from public, anon, authenticated;
revoke all on sequence public.quotation_cost_notes_id_seq from public, anon, authenticated;
revoke all on sequence public.quotation_files_id_seq from public, anon, authenticated;

grant all on table public.quotations to service_role;
grant all on table public.quotation_items to service_role;
grant all on table public.quotation_cost_notes to service_role;
grant all on table public.quotation_files to service_role;
grant usage, select on sequence public.quotation_items_id_seq to service_role;
grant usage, select on sequence public.quotation_cost_notes_id_seq to service_role;
grant usage, select on sequence public.quotation_files_id_seq to service_role;

revoke all on function public.quotation_safe_numeric(text,numeric) from public, anon, authenticated;
revoke all on function public.quotation_safe_integer(text,integer) from public, anon, authenticated;
revoke all on function public.quotation_safe_bigint(text,bigint) from public, anon, authenticated;
revoke all on function public.quotation_safe_date(text,date) from public, anon, authenticated;
revoke all on function public.quotation_safe_timestamptz(text,timestamptz) from public, anon, authenticated;
revoke all on function public.validate_quotation_session_for_service(uuid) from public, anon, authenticated;
revoke all on function public.sync_quotation_from_drive(uuid,jsonb) from public, anon, authenticated;
revoke all on function public.reconcile_quotation_from_drive(jsonb) from public, anon, authenticated;
revoke all on function public.quotation_sync_from_drive_core(uuid,jsonb,boolean) from public, anon, authenticated, service_role;

grant execute on function public.validate_quotation_session_for_service(uuid) to service_role;
grant execute on function public.sync_quotation_from_drive(uuid,jsonb) to service_role;
grant execute on function public.reconcile_quotation_from_drive(jsonb) to service_role;
